"""add chunk embeddings

Revision ID: 086a1d12e112
Revises: 4e3a0c7eadf7
Create Date: 2026-09-26 13:39:15.789976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision: str = '086a1d12e112'
down_revision: Union[str, Sequence[str], None] = '4e3a0c7eadf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_chunks', 'embedding')
    # ### end Alembic commands ###
