"""create repository chunks

Revision ID: 4e3a0c7eadf7
Revises: 98d2d46f7478
Create Date: 2026-09-26 11:26:00.594835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3a0c7eadf7'
down_revision: Union[str, Sequence[str], None] = '98d2d46f7478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'start_line', 'end_line', name='uq_repository_chunk_location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_chunks')
    # ### end Alembic commands ###
