"""add repository file uniqueness

Revision ID: 98d2d46f7478
Revises: ff62212f223e
Create Date: 2026-09-25 19:41:42.021421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d2d46f7478'
down_revision: Union[str, Sequence[str], None] = 'ff62212f223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_repository_file_path', 'repository_files', ['repository_id', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repository_file_path', 'repository_files', type_='unique')
    # ### end Alembic commands ###
